default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: tech_comunication_app_development
  adapter: sqlite3

test:
  <<: *default
  database: tech_comunication_app_test
  adapter: sqlite3

production:
  <<: *default
  database: tech_comunication_app_production
  username: tech_comunication_app
  password: <%= ENV['TECH_COMUNICATION_APP_DATABASE_PASSWORD'] %>
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  encoding: unicode
  pool: 5
